version: '3'
services:
  service1:
    build: ./app_folder
    ports:
      - "3000"
  service2:
    build: ./vote_folder
    ports:
      - "3001:3000"
  service3:
    build: ./notifications_folder
    ports:
      - "3002:3000"